import Footer from "@/app/_components/navigation/footer"
import Header from "@/app/_components/navigation/header"
import type { Metadata } from "next"
import { ReactNode } from "react"
import "./globals.css"

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="ja">
      <body className="flex h-screen flex-col bg-blueGray">
        <Header />
        <main className="mx-auto max-w-4xl flex-1 px-6">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
