import Footer from "@/components/navigation/footer"
import Header from "@/components/navigation/header"
import { clsx } from "clsx"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body className={clsx(`${inter.className} bg-blue-gray`)}>
        <Header />
        <main className="h-[80vh]">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
